controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_page_route:
  path: /nouvelle-page
  controller: App\Controller\YourController::yourMethod


home_page_route:
    path: /home   # Le chemin URL associé à cette route
    controller: App\Controller\VotreController::connection    # Le contrôleur et la méthode associés à cette route


test_database_connection:
    path: /test-database-connection
    controller: App\Controller\DatabaseTestController::testDatabaseConnection

# DATABASE_URL="mysql://app:benoit73:Xmzsse6429?@mysql-benoit73.alwaysdata.net:3306/app?serverVersion=8.0.32&charset=utf8mb4"
